apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: zkpok
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/zkpok-healthcheck:5d5ae8800621e134eafff1ce04f0fb15f36119ac0368ac2433b82e7c0d94de26
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/zkpok-challenge:14dd553e9a5924804283ca2fefbaa9e1fb6bd71073c4e61cea9ad49482608021
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
