apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: desfunctional
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/desfunctional-healthcheck:ece3f9af4b551e7a5e03cbfb2dfb5e11550659b6af000a15edf91cd8d1dbda85
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/desfunctional-challenge:5d6366f88d6a90262bc7a75efef614cc51fda95cf3b09d43f371b1fec6a1563e
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
