apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: fasterbox
spec:
  deployed: true
  powDifficultySeconds: 10
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/fasterbox-healthcheck:502c3282c7643c718fb965190998483b8bf28401211de803ad140f4c2aa0c7fd
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/fasterbox-challenge:c1e83ccb90f92b1086b913605b08ab03f0c4c8bdd153484079e364fa7252cf56
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                cpu: "2"
                memory: "8Gi"
            volumeMounts:
              - name: kvm-volume
                mountPath: /dev/kvm
            securityContext:
              privileged: true
        volumes:
          - name: kvm-volume
            hostPath:
              path: /dev/kvm
        nodeSelector:
          nested-virtualization: enabled
        tolerations:
          - key: "nested-virtualization"
            operator: "Equal"
            value: "enabled"
            effect: "NoExecute"
