apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: in-the-shadows
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/in-the-shadows-healthcheck:3b06521e028b08b7ed69909394f687347dee32459fa51f9f267c63284ef42fde
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/in-the-shadows-challenge:0dc2dba9becbf012e7e5785d2aa56e1b58128bb09a2c4b37b0ea237ec01f6e1c
  allowConnectTo:
    - in-the-shadows-bot
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
            env:
              - name: XSSBOT_HOST
                value: "in-the-shadows-bot"
              - name: XSSBOT_PORT
                value: "1337"
              - name: RECAPTCHA_SITE_KEY
                value: "6Leagf8pAAAAACE_Dbk6aahufjuJ5HWAQ0ebVCa-"
              - name: RECAPTCHA_SECRET_KEY
                value: "6Leagf8pAAAAALgKmmDPf4MtRYioi0i2H9FGxpiK"
