apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: unicornel
spec:
  deployed: true
  powDifficultySeconds: 10
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/unicornel-healthcheck:67303f211533cad0827d6b50ac1d0abdd335ea1149e5fd92564ae7b2230675dd
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/unicornel-challenge:c0b775a056beb43abb2f1de30980117e5338ad67808b80a882c25e96415531c6
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
