apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: auxin2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/auxin2-healthcheck:05e785dd9a4103e701047dbaf7f6ccfdcce866519837fcf1e38baebb22db121e
  image: europe-west4-docker.pkg.dev/gctf-2024/kctf-cluster-challenges/auxin2-challenge:6721af757ef2ecaecc5065f80a2297412dd5ddfdc337a43bc9bd381c64ac8dc3
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
